### ISSUE TITLE
Sefrou-Ramal hits unit cap after capturing base

### ISSUE THREAD

**Issue by mplorentz** [tbox1911/Liberation-RX#55]
We tried to start a campaign on Sefrou-Ramal today but every time we captured a point we would get the warning about the unit cap being exceeded, and then our fps would drop to 3 and we had to restart the server. We captured 3 bases this way before giving up. We know the server is powerful enough because we just finished playing Liberation RX on Stratis on the same dedicated server and it we had great fps.

I'm happy to grab any debug information you might need if you can't reproduce the issue.

**Comment by tbox1911** [comment]
I'll try to reproduce the issue on my side.

btw, can you send me the server rpt when the game drop fps

the maximum enemy unit is defined in "gameplay_constants.sqf"
GRLIB_sector_cap = 180;
 
in the status info (bottom left on map view) you have the count for all units
is the opfror count reach 180 ?

thanks

**Comment by mplorentz** [comment]
Thanks for the quick update! We will give the new build a try and I'll report back.

**Comment by tbox1911** [comment]
Hope the latest version will solve your problem,
yesterday, with 4/6 players, we tested the latest version on WS + R3F Mod  

my server is a small box  (2cpu / 1.8Gh)

here are the statistics:

23:57:39 "--- LRX Garbage Collector --- Run at: 47021 - Delete: 83 objects - 51.2821 fps"
0:07:52 "--- LRX Garbage Collector --- Run at: 47634 - Delete: 4 objects - 49.5356 fps"
...
4:37:44 "--- LRX Garbage Collector --- Run at: 63709 - Delete: 24 objects - 42.2164 fps"
4:48:30 "--- LRX Garbage Collector --- Run at: 64341 - Delete: 58 objects - 24.9221 fps"
4:58:53 "--- LRX Garbage Collector --- Run at: 64960 - Delete: 41 objects - 49.0798 fps"

the number after " Run at: " s the number of seconds elapsed since the server start 
64960 means  (64960 / 60 / 60  = 18)  server is running for 18 hours non stop !

on heavy actions, the server goes down to ~ 18/20 fps then quickly returns to ~ 45/50

**Comment by mplorentz** [comment]
@tbox1911 this solved it! Thanks so much for your quick updates. Liberation RX is quickly becoming our favorite mission.
